VIB_PATTERN_CHANGED = "VIB_PATTERN_CHANGED"

VIB_RENAMED = "VIB_RENAMED"

VIB_STARTED_SENDING = "VIB_STARTED_SENDING"

VIB_FINISHED_SENDING = "VIB_FINISHED_SENDING"

MESSENGER_CONNECTED = "MESSENGER_CONNECTED"

MESSENGER_DISCONNECTED = "MESSENGER_DISCONNECTED"
